# SPDX-License-Identifier: LGPL-3.0-only

# This file contains the pipelines that run on the Astron repository of Radler,
# which is at https://git.astron.nl/RD/radler

.dind-requester:
  tags:
    - dind

# At Astron, the cibuild-python-wheels job needs this custom configuration.
.cibuildwheels-custom:
  extends: .dind-requester
  variables:
    DOCKER_HOST: tcp://docker:2375

include: .gitlab-ci.common.yml

deploy_on_test_pypi:
  extends: .deploy-python-package
  environment: pypi-test
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: ${TESTPYPI_TOKEN}
    TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/

deploy_on_pypi:
  extends: .deploy-python-package
  environment: pypi
  variables:
    TWINE_USERNAME: __token__
    TWINE_PASSWORD: ${PYPI_TOKEN}
    TWINE_REPOSITORY_URL: https://upload.pypi.org/legacy/
